//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBColaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBColaborador()
        {
            this.TBRevision = new HashSet<TBRevision>();
        }
    
        public int ColaboradorID { get; set; }
        public string IdentificacionColaboradorFK { get; set; }
        public int TipoColaborador { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UserUltimaModificacion { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
    
        public virtual TBPersona TBPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBRevision> TBRevision { get; set; }
    }
}
