//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBEntregaCasos
    {
        public int Id { get; set; }
        public string Caso { get; set; }
        public int Mensajero { get; set; }
        public int JuntaFK { get; set; }
        public string AsignadoFK { get; set; }
        public int Recepcion { get; set; }
        public int TipoPagoFK { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Transferencia { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UserUltimaModificacion { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
    
        public virtual TBPersona TBPersona { get; set; }
        public virtual TBInstitucion TBInstitucion { get; set; }
        public virtual TBMensajero TBMensajero { get; set; }
        public virtual TBTipoRecepcion TBTipoRecepcion { get; set; }
        public virtual TBTipoPago TBTipoPago { get; set; }
    }
}
