//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBRevision
    {
        public int IdCaso { get; set; }
        public string Consecutivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaAsignada { get; set; }
        public System.DateTime FechaRevisada { get; set; }
        public string Comentario { get; set; }
        public int TramitadorFK { get; set; }
        public int CodigoJuntaFK { get; set; }
        public int Recepcion { get; set; }
        public string numeroActa { get; set; }
        public string numeroFolio { get; set; }
        public Nullable<System.DateTime> fechaActa { get; set; }
        public bool Estado { get; set; }
        public string UserUltimaModificacion { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
    
        public virtual TBColaborador TBColaborador { get; set; }
        public virtual TBInstitucion TBInstitucion { get; set; }
    }
}
